openapi: 3.0.1
info:
  title: DD online helper
  version: 0.0.1
paths:
  /last-events:
    get:
      summary: Get the last events
      parameters:
        - name: after
          in: query
          required: false
          schema:
            type: string
        - name: room
          in: query
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - timestamp
                    - text
                  properties:
                    timestamp:
                      type: string
                      format: date-time
                    text:
                      type: string
                      minLength: 1

  /dice:
    post:
      summary: Throw some dice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [room, player, dice]
              properties:
                room:
                  type: string
                  minLength: 1
                player:
                  type: string
                  minLength: 1
                dice:
                  type: array
                  items:
                    type: object
                    properties:
                      numberOfSides:
                        type: integer
                        minimum: 1
                      numberOfDice:
                        type: integer
                        minimum: 1
      responses:
        "200":
          description: OK

